### ISSUE TITLE
With sorted cell populations as the sample, sampleMetadataFromCellColData does not work

### ISSUE THREAD

**Issue by SamirRachidZaim-AIFI** [aifimmunology/MOCHA#76]
callOpenTiles/sampleMetadataFromCellColData not extracting columns of interest from metadata when "sampleSpecific=FALSE"

**Comment by markphillippebworth** [comment]
We no longer support non-sample specific analysis. If you want to call tiles in ways that are not sample specific, then please extracte the fragment files by sample and cell type, and then merge samples by cell type before passing that GRangesList to callOpenTiles. You will also need to adjust the Sample column of the metadata to reflect this change so that MOCHA can align metadata and the GRangesList. 

And as a reminder, please ensure that the rownames of the single cell metadata are preserved, since that will help MOCHA align metadata and single cells within the GRangesList.
